@abstract
class_name GDObjectFrames
## Maps Geometry Dash object IDs to atlas frame names.
##
## The table is generated by [code]tools/build_object_frames.py[/code] from
## [code]tools/gd_object_id_list.txt[/code] (object ID -> base frame name), the
## sprite-tree table in [code]tools/gdrweb_objects.json[/code] (which child
## sprites an object is built from, and how each is placed) and the shipped
## atlas sheets, which supply the matching [code]_color_[/code] (detail) and
## [code]_glow_[/code] frames. Every entry is backed by a frame that provably
## exists in the bundled atlas.
##
## The generated table lives in
## [code]assets/textures/gd_atlas/object_frames.json[/code]. Additions and
## corrections can be supplied via [constant USER_MAP_PATH], which is merged
## over the generated table.
##
## Which [i]colour channel[/i] each layer follows by default is a separate
## question, answered by [GMDDefaultChannels].

## The generated, ID-derived mapping.
const GENERATED_MAP_PATH: String = "res://assets/textures/gd_atlas/object_frames.json"

## Optional user additions/corrections, merged last so it always wins.
const USER_MAP_PATH: String = "user://gd_object_frames.json"

## Colour classes a sprite can belong to. A [i]base[/i] sprite follows the
## object's main colour channel, a [i]detail[/i] sprite its secondary channel,
## and a [i]black[/i] sprite is always drawn black, as in Geometry Dash.
const COLOR_BASE: String = "base"
const COLOR_DETAIL: String = "detail"
const COLOR_BLACK: String = "black"

## The frame Geometry Dash gives objects whose root sprite draws nothing; all
## of their artwork lives in [member ObjectFrames.parts].
const EMPTY_FRAME: String = "emptyFrame.png"

## Marker for "no default z known"; real defaults are small odd numbers.
const Z_UNKNOWN: int = -9999


## One object's layered artwork.
class ObjectFrames:
	extends RefCounted

	## Main sprite, always present. May be [constant EMPTY_FRAME] for objects
	## drawn entirely from [member parts].
	var base: String = ""
	## Recolourable secondary layer, empty when the object has none. Only used
	## by objects whose sprite tree is not known; those that are carry their
	## detail sprites in [member parts] instead.
	var detail: String = ""
	## Additive glow layer, empty when the object has none.
	var glow: String = ""
	## Colour class of the root sprite: [constant COLOR_BASE] or
	## [constant COLOR_BLACK].
	var color: String = COLOR_BASE
	## Opacity Geometry Dash gives the root sprite itself, before any channel
	## or per-object opacity.
	var opacity: float = 1.0
	## Where Geometry Dash draws the object when the level string doesn't say
	## (keys 24/25 absent): its default z layer (1 = B2, 3 = B1, 5 = T1, ...)
	## and fine z order within that layer. [constant Z_UNKNOWN] when the
	## object table doesn't cover this id.
	var default_z_layer: int = Z_UNKNOWN
	var default_z_order: int = Z_UNKNOWN
	## Extra sprites the object is drawn from, in draw order. Each is a
	## [Dictionary] with:
	## [codeblock]
	## frame   String  atlas frame name
	## order   int     negative: drawn behind the root sprite; positive: in front
	## x, y    float   centre, in Geometry Dash units (30 per cell, y up)
	## rot     float   degrees, anticlockwise
	## sx, sy  float   scale; negative to mirror
	## ax, ay  float   anchor, as a fraction of the frame size from its centre
	## color   String  colour class, "base" when absent
	## opacity float   sprite's own opacity, 1 when absent
	## [/codeblock]
	## Missing keys take their defaults.
	var parts: Array[Dictionary] = []

	func has_detail() -> bool:
		return not detail.is_empty()

	func has_glow() -> bool:
		return not glow.is_empty()

	func has_parts() -> bool:
		return not parts.is_empty()

	## Whether the root sprite itself draws anything.
	func has_visible_root() -> bool:
		return base != EMPTY_FRAME

	## [code]true[/code] when any sprite follows the secondary colour channel:
	## a legacy detail frame, or a part of the detail colour class.
	func has_detail_layer() -> bool:
		if has_detail():
			return true
		for part: Dictionary in parts:
			if str(part.get("color", COLOR_BASE)) == COLOR_DETAIL:
				return true
		return false

	## [code]true[/code] when any sprite is drawn black.
	func has_black_layer() -> bool:
		if color == COLOR_BLACK:
			return true
		for part: Dictionary in parts:
			if str(part.get("color", COLOR_BASE)) == COLOR_BLACK:
				return true
		return false


static var _map: Dictionary[int, ObjectFrames]
static var _loaded: bool = false


## Frames for an object ID, or [code]null[/code] when unmapped.
static func get_frames(gd_id: int) -> ObjectFrames:
	if not _loaded:
		reload()
	return _map.get(gd_id)


static func has_frames(gd_id: int) -> bool:
	if not _loaded:
		reload()
	return _map.has(gd_id)


## Number of mapped objects, for diagnostics.
static func count() -> int:
	if not _loaded:
		reload()
	return _map.size()


## Re-reads both mappings from disk.
static func reload() -> void:
	_loaded = true
	_map = { }
	_merge_file(GENERATED_MAP_PATH)
	_merge_file(USER_MAP_PATH)


static func _merge_file(path: String) -> void:
	if not FileAccess.file_exists(path):
		return
	var text: String = FileAccess.get_file_as_string(path)
	if text.is_empty():
		return
	var parsed: Variant = JSON.parse_string(text)
	if parsed is not Dictionary:
		push_warning("GDObjectFrames: %s isn't a JSON object" % path)
		return

	# Both the generated file ({"frames": {...}}) and a hand-written flat file
	# ({"1": "name.png"}) are accepted.
	var frames: Variant = parsed.get("frames", parsed)
	if frames is not Dictionary:
		return

	for key: String in frames:
		if key.begins_with("_") or not key.is_valid_int():
			continue
		var value: Variant = frames[key]
		var entry := ObjectFrames.new()
		if value is String:
			entry.base = value
		elif value is Dictionary:
			entry.base = str(value.get("base", ""))
			entry.detail = str(value.get("detail", ""))
			entry.glow = str(value.get("glow", ""))
			entry.color = str(value.get("color", COLOR_BASE))
			entry.opacity = clampf(float(value.get("opacity", 1.0)), 0.0, 1.0)
			entry.default_z_layer = int(value.get("zl", Z_UNKNOWN))
			entry.default_z_order = int(value.get("zo", Z_UNKNOWN))
			var raw_parts: Variant = value.get("parts", [])
			if raw_parts is Array:
				for raw_part: Variant in raw_parts:
					if raw_part is Dictionary and not str(raw_part.get("frame", "")).is_empty():
						entry.parts.append(raw_part)
		if not entry.base.is_empty():
			_map[int(key)] = entry
