@abstract
class_name GDObjectFrames
## Maps Geometry Dash object IDs to atlas frame names.
##
## The table is generated by [code]tools/build_object_frames.py[/code] from
## [code]tools/gd_object_id_list.txt[/code] (object ID -> base frame name) and
## the shipped atlas plists, which supply the matching [code]_color_[/code]
## (detail) and [code]_glow_[/code] frames. Every entry is backed by a frame
## that provably exists in the bundled atlases.
##
## The generated table lives in
## [code]assets/textures/gd_atlas/object_frames.json[/code]. Additions and
## corrections can be supplied via [constant USER_MAP_PATH], which is merged
## over the generated table.
##
## Which [i]colour channel[/i] each layer follows by default is a separate
## question, answered by [GMDDefaultChannels].

## The generated, ID-derived mapping.
const GENERATED_MAP_PATH: String = "res://assets/textures/gd_atlas/object_frames.json"

## Optional user additions/corrections, merged last so it always wins.
const USER_MAP_PATH: String = "user://gd_object_frames.json"


## One object's layered artwork.
class ObjectFrames:
	extends RefCounted

	## Main sprite, always present.
	var base: String = ""
	## Recolourable secondary layer, empty when the object has none.
	var detail: String = ""
	## Additive glow layer, empty when the object has none.
	var glow: String = ""

	func has_detail() -> bool:
		return not detail.is_empty()

	func has_glow() -> bool:
		return not glow.is_empty()


static var _map: Dictionary[int, ObjectFrames]
static var _loaded: bool = false


## Frames for an object ID, or [code]null[/code] when unmapped.
static func get_frames(gd_id: int) -> ObjectFrames:
	if not _loaded:
		reload()
	return _map.get(gd_id)


static func has_frames(gd_id: int) -> bool:
	if not _loaded:
		reload()
	return _map.has(gd_id)


## Number of mapped objects, for diagnostics.
static func count() -> int:
	if not _loaded:
		reload()
	return _map.size()


## Re-reads both mappings from disk.
static func reload() -> void:
	_loaded = true
	_map = { }
	_merge_file(GENERATED_MAP_PATH)
	_merge_file(USER_MAP_PATH)


static func _merge_file(path: String) -> void:
	if not FileAccess.file_exists(path):
		return
	var text: String = FileAccess.get_file_as_string(path)
	if text.is_empty():
		return
	var parsed: Variant = JSON.parse_string(text)
	if parsed is not Dictionary:
		push_warning("GDObjectFrames: %s isn't a JSON object" % path)
		return

	# Both the generated file ({"frames": {...}}) and a hand-written flat file
	# ({"1": "name.png"}) are accepted.
	var frames: Variant = parsed.get("frames", parsed)
	if frames is not Dictionary:
		return

	for key: String in frames:
		if key.begins_with("_") or not key.is_valid_int():
			continue
		var value: Variant = frames[key]
		var entry := ObjectFrames.new()
		if value is String:
			entry.base = value
		elif value is Dictionary:
			entry.base = str(value.get("base", ""))
			entry.detail = str(value.get("detail", ""))
			entry.glow = str(value.get("glow", ""))
		if not entry.base.is_empty():
			_map[int(key)] = entry
