@abstract
class_name MonsterAnimations
## Monster animation table for Geometry Dash's animated objects (Big Beast
## 918, monsters 1327/1328, Bat 1584, Spikeball 2012) and the Animate
## trigger (1585, key 76).
##
## Generated by [code]tools/build_monster_animations.py[/code] from the game's
## objectDefinitions.plist (per-animation frame count, delay, loop flag,
## default animation) and GJBeastNN_AnimDesc.plist (per-frame part sprite
## placement). Part entries are
## [code][texture, x, y, sx, sy, rotation_deg, flip_x, flip_y, z][/code] in
## the conventions of object_frames.json: Geometry Dash units around the
## object's centre, y up, rotation clockwise.

const TABLE_PATH: String = "res://assets/textures/gd_atlas/monster_animations.json"

const PART_TEXTURE: int = 0
const PART_X: int = 1
const PART_Y: int = 2
const PART_SX: int = 3
const PART_SY: int = 4
const PART_ROT: int = 5
const PART_FLIP_X: int = 6
const PART_FLIP_Y: int = 7

## Rest-position tolerance, in Geometry Dash units, for binding a sprite the
## animation does not name (an overlay or glow copy) to the animated sprite
## it sits on.
const BIND_DISTANCE: float = 0.5

static var _table: Dictionary = {}
static var _loaded: bool = false


static func _ensure_loaded() -> void:
	if _loaded:
		return
	_loaded = true
	var file := FileAccess.open(TABLE_PATH, FileAccess.READ)
	if file == null:
		return
	var parsed: Variant = JSON.parse_string(file.get_as_text())
	if parsed is Dictionary:
		_table = parsed


## Monster name ("GJBeast01"...) for [param gd_id], or empty.
static func monster_for(gd_id: int) -> String:
	_ensure_loaded()
	return str(_table.get("objects", {}).get(str(gd_id), ""))


static func monster(name: String) -> Dictionary:
	_ensure_loaded()
	return _table.get("monsters", {}).get(name, {})


## Animation name for the Animate trigger's key 76, or empty when the
## monster has no such ID.
static func name_for_id(name: String, animation_id: int) -> String:
	var ids: Array = monster(name).get("ids", [])
	if animation_id < 0 or animation_id >= ids.size():
		return ""
	return str(ids[animation_id])


## Index of the sprite in [param sprites] (one animation frame) that a
## static sprite with [param frame_name] at rest position [param rest]
## follows: same texture (glow copies follow their base sprite) nearest to
## the rest position, else any sprite sharing the rest position; -1 when
## the animation does not move it.
static func bind_sprite(sprites: Array, frame_name: String, rest: Vector2) -> int:
	var texture: String = frame_name.replace("_glow", "")
	var best: int = -1
	var best_distance: float = INF
	for index: int in sprites.size():
		var sprite: Array = sprites[index]
		if str(sprite[PART_TEXTURE]) != texture:
			continue
		var distance: float = rest.distance_to(Vector2(sprite[PART_X], sprite[PART_Y]))
		if distance < best_distance:
			best = index
			best_distance = distance
	if best != -1:
		return best
	for index: int in sprites.size():
		var sprite: Array = sprites[index]
		if rest.distance_to(Vector2(sprite[PART_X], sprite[PART_Y])) <= BIND_DISTANCE:
			return index
	return -1


## Object-local placement of one animation sprite, in world units; the
## same construction as GDDecorationLoader._add_part's local transform.
static func sprite_local(sprite: Array) -> Transform2D:
	var gd_to_world: float = float(Constants.CELL_SIZE) / GMDConverter.GD_CELL_SIZE
	var scale := Vector2(
			float(sprite[PART_SX]) * (-1.0 if int(sprite[PART_FLIP_X]) != 0 else 1.0),
			float(sprite[PART_SY]) * (-1.0 if int(sprite[PART_FLIP_Y]) != 0 else 1.0),
	)
	return Transform2D(
			-deg_to_rad(float(sprite[PART_ROT])),
			scale,
			0.0,
			Vector2(float(sprite[PART_X]), -float(sprite[PART_Y])) * gd_to_world,
	)


## Sprite placement as GDDecorationLoader._add_layer builds it: the art
## scale folded into the basis, the atlas trim offset through the basis.
static func placement(object_local: Transform2D, art_scale_factor: float, trim_offset: Vector2) -> Transform2D:
	var result := object_local
	result.x *= art_scale_factor
	result.y *= art_scale_factor
	result.origin = object_local.origin + object_local.basis_xform(Vector2(trim_offset.x, -trim_offset.y) * art_scale_factor)
	return result
